# Generated by Django 6.0.4 on 2026-04-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_app', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='Guest', max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('netbanking', 'NetBanking'), ('cash', 'Cash'), ('card', 'Card')], default='cash', max_length=20)),
                ('items', models.TextField(blank=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('gst', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField()),
                ('status', models.CharField(choices=[('invalid', 'Invalid'), ('failed', 'Failed')], default='failed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
